// Generated by CoffeeScript 1.9.2
(function() {
  var c, http, port, server, t;

  t = require('socketstream');

  http = require('http');

  c = function() {
    return console.log.apply(console, arguments);
  };

  t.client.define('basic', {
    view: 'basic.jade',
    code: ['app', 'libs']
  });

  t.http.route('/', function(req, res) {
    return res.serveClient('basic');
  });

  t.client.formatters.add(require('ss-coffee'));

  t.client.formatters.add(require('ss-jade'));

  t.session.store.use('redis');

  t.publish.transport.use('redis');

  server = http.createServer(t.http.middleware);

  t.start(server);

  process.on('uncaughtException', function(e) {
    return c('Exception caught', e);
  });

  port = 3000;

  server.listen(port);

  setInterval(function() {
    c("hey");
    return t.api.publish.all("hey");
  }, 2200);

}).call(this);
