// Generated by CoffeeScript 1.9.2
(function() {
  var c, http, port, server, t;

  t = require('socketstream');

  http = require('http');

  t.session.options = "SocketStream";

  c = function() {
    return console.log.apply(console, arguments);
  };

  t.client.define('basic', {
    view: 'basic.jade',
    code: ['app', 'libs'],
    css: ['app']
  });

  t.client.define('another', {
    view: 'basic.jade',
    code: ['another', 'libs'],
    css: ['another']
  });

  t.http.route('/testing', function(req, res) {
    var i, item, len, ref;
    c("yes");
    c("(http) req.session", Object.keys(req.session));
    ref = Object.keys(res);
    for (i = 0, len = ref.length; i < len; i++) {
      item = ref[i];
      if (typeof res[item] === 'function') {
        c(item);
      }
    }
    res.write(Date.now() + "   hi");
    return res.end();
  });

  t.http.route('/another', function(req, res) {
    return res.serveClient('another');
  });

  t.http.route('/', function(req, res) {
    c("(http) req.session", Object.keys(req.session));
    c('signedCookies', Object.keys(req.signedCookies));
    c("signedCookies['connect.sid']", req.signedCookies['connect.sid']);
    return res.serveClient('basic');
  });

  t.client.formatters.add(require('ss-coffee'));

  t.client.formatters.add(require('ss-jade'));

  t.client.formatters.add(require('ss-stylus'));

  t.session.store.use('redis', {
    secret: "SocketStream"
  });

  t.publish.transport.use('redis', {
    secret: "SocketStream"
  });

  server = http.createServer(t.http.middleware);

  t.start(server);

  process.on('uncaughtException', function(e) {
    return c('Exception caught', e);
  });

  port = 3000;

  server.listen(port);

  setInterval(function() {
    return t.api.publish.all("hey", Math.random());
  }, 2200);

}).call(this);
